
package Paciente;

import javax.swing.JOptionPane;

/**
 *
 * @author Yuliana Ruiz
 */
public class JfrmPaciente extends javax.swing.JFrame {

    String [][] Paciente = new  String [4][5];
    String [][] Afiliacion = new  String [5][3];
    int fil = 0;
    int fil1 = 0;
    int pos = 0;
    
    public JfrmPaciente() {
        initComponents();
        OcultarPanel();
    }
    
    protected void OcultarPanel()
    {
        pnlPaciente.setVisible(false);
        pnlAfiliacion.setVisible(false);
        pnlCitas.setVisible(false);
    }
    
     protected void GuardarRegistroPaciente()
    {
        Paciente[fil][0] = txt_Identificacion.getText();
        Paciente[fil][1] = txt_Nombre.getText();
        Paciente[fil][2] = txt_Apellido.getText();
        Paciente[fil][3] = txt_telefono.getText();
        fil++;
    }
     
       protected void GuardarRegistroAfiliacion()
    {
        
        Afiliacion[fil1][0] = txt_ID.getText();
        int EPS = cbx_EPS.getSelectedIndex();
        lbl_Afiliacion.setText("" + EPS);
        Afiliacion[fil1][1] = lbl_Afiliacion.getText();
        Afiliacion[fil1][2] = txt_Fecha.getText();
        fil1++;
    }
     protected void BuscarRegistroPaciente()
     {
        int aux = 0, sw = 0; 
        while(aux <=3)
        {
            if(txt_Identificacion.getText().equals(Paciente[aux][0]))
            {
             pos = aux;
                sw = 1;
            }
            aux++;
        }
        if(sw == 0)
                {
                    JOptionPane.showMessageDialog(null, "No hay registros");
                }
        if(sw == 1)
        {        
        txt_Identificacion.setText("" + Paciente [pos][0]);
        txt_Nombre.setText("" + Paciente [pos][1]);
        txt_Apellido.setText("" + Paciente[pos][2]);
        txt_telefono.setText("" + Paciente[pos][3]);
        }
        
     }
     
     protected void BuscarRegistroAfiliacion()
     {
        int aux1 = 0,pos1 = 0, sw1 = 0; 
        while(aux1 <=4)
        {
            if(txt_ID.getText().equals(Afiliacion[aux1][0]))
            {
      
            pos1 = aux1;
                sw1 = 1;
            }
            aux1++;
        }
        if(sw1 == 0)
                {
                    JOptionPane.showMessageDialog(null, "No hay registros");
                }
        if(sw1 == 1)
        {        
        txt_Nomb.setText("" + Afiliacion [pos1][1]);
        txt_Apellid.setText("" + Paciente[pos1][2]);
        }
        
     }
     
     
     protected void ActualizarAfiliacion()
     {
         Paciente[pos][1]= txt_Nombre.getText();
         Paciente[pos][2]= txt_Apellido.getText();
         Paciente[pos][3]= txt_telefono.getText();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Menu = new javax.swing.JPanel();
        btnPaciente = new javax.swing.JButton();
        btnAfiliacion = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlPaciente = new javax.swing.JPanel();
        lbIdentificacionl = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        txt_Identificacion = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        btn_Actualizar = new javax.swing.JButton();
        pnlAfiliacion = new javax.swing.JPanel();
        lbl_ID = new javax.swing.JLabel();
        lbl_Nomb = new javax.swing.JLabel();
        lbl_Apell = new javax.swing.JLabel();
        lbl_Fecha = new javax.swing.JLabel();
        lbl_EPS = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_Nomb = new javax.swing.JTextField();
        txt_Fecha = new javax.swing.JTextField();
        txt_Apellid = new javax.swing.JTextField();
        cbx_EPS = new javax.swing.JComboBox<>();
        btn_Guard = new javax.swing.JButton();
        btn_BuscarAfili = new javax.swing.JButton();
        lbl_Afiliacion = new javax.swing.JLabel();
        pnlCitas = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Menu.setBackground(new java.awt.Color(255, 51, 255));

        btnPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPaciente.setText("Paciente");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });

        btnAfiliacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAfiliacion.setText("Afiliación");
        btnAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfiliacionActionPerformed(evt);
            }
        });

        btnCitas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCitas.setText("Citas");
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_MenuLayout = new javax.swing.GroupLayout(pnl_Menu);
        pnl_Menu.setLayout(pnl_MenuLayout);
        pnl_MenuLayout.setHorizontalGroup(
            pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCitas)
                    .addComponent(btnAfiliacion)
                    .addComponent(btnPaciente))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnl_MenuLayout.setVerticalGroup(
            pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MenuLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnPaciente)
                .addGap(18, 18, 18)
                .addComponent(btnAfiliacion)
                .addGap(18, 18, 18)
                .addComponent(btnCitas)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        pnlPaciente.setBackground(new java.awt.Color(255, 204, 204));

        lbIdentificacionl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIdentificacionl.setText("Identificacion");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellido.setText("Apellido");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefono.setText("Telefono");

        btn_Guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        txt_Identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdentificacionActionPerformed(evt);
            }
        });

        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });

        txt_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoActionPerformed(evt);
            }
        });

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPacienteLayout = new javax.swing.GroupLayout(pnlPaciente);
        pnlPaciente.setLayout(pnlPacienteLayout);
        pnlPacienteLayout.setHorizontalGroup(
            pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacienteLayout.createSequentialGroup()
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPacienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPacienteLayout.createSequentialGroup()
                                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIdentificacionl)
                                    .addComponent(lblNombre)
                                    .addComponent(lblTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnlPacienteLayout.createSequentialGroup()
                                .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)))
                        .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Guardar)
                        .addGap(31, 31, 31)
                        .addComponent(btn_Buscar)
                        .addGap(35, 35, 35)
                        .addComponent(btn_Actualizar)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        pnlPacienteLayout.setVerticalGroup(
            pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificacionl)
                    .addComponent(txt_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar)
                    .addComponent(btn_Buscar)
                    .addComponent(btn_Actualizar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlAfiliacion.setBackground(new java.awt.Color(255, 153, 153));

        lbl_ID.setText("Identificacion");

        lbl_Nomb.setText("Nombre");

        lbl_Apell.setText("Apelidos");

        lbl_Fecha.setText("Fecha");

        lbl_EPS.setText("EPS");

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        txt_Nomb.setEnabled(false);
        txt_Nomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombActionPerformed(evt);
            }
        });

        txt_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FechaActionPerformed(evt);
            }
        });

        txt_Apellid.setEnabled(false);
        txt_Apellid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidActionPerformed(evt);
            }
        });

        cbx_EPS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sura", "Comeva", "Savia Salud", "Nueva EPS", " ", " " }));

        btn_Guard.setText("Guardar");
        btn_Guard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardActionPerformed(evt);
            }
        });

        btn_BuscarAfili.setText("Buscar");
        btn_BuscarAfili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarAfiliActionPerformed(evt);
            }
        });

        lbl_Afiliacion.setText("jLabel2");

        javax.swing.GroupLayout pnlAfiliacionLayout = new javax.swing.GroupLayout(pnlAfiliacion);
        pnlAfiliacion.setLayout(pnlAfiliacionLayout);
        pnlAfiliacionLayout.setHorizontalGroup(
            pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAfiliacionLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btn_Guard)
                .addGap(26, 26, 26)
                .addComponent(btn_BuscarAfili)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAfiliacionLayout.createSequentialGroup()
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAfiliacionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Nomb)
                            .addComponent(lbl_Apell)
                            .addComponent(lbl_Fecha)
                            .addComponent(lbl_EPS))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAfiliacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_ID)
                        .addGap(18, 18, 18)))
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txt_Nomb, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txt_ID)
                    .addComponent(txt_Apellid, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(cbx_EPS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(lbl_Afiliacion)
                .addGap(71, 71, 71))
        );
        pnlAfiliacionLayout.setVerticalGroup(
            pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAfiliacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ID)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nomb)
                    .addComponent(txt_Nomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAfiliacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Apell)
                            .addComponent(txt_Apellid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAfiliacionLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_Afiliacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Fecha)
                    .addComponent(txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_EPS)
                    .addComponent(cbx_EPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(pnlAfiliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guard)
                    .addComponent(btn_BuscarAfili))
                .addContainerGap())
        );

        pnlCitas.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout pnlCitasLayout = new javax.swing.GroupLayout(pnlCitas);
        pnlCitas.setLayout(pnlCitasLayout);
        pnlCitasLayout.setHorizontalGroup(
            pnlCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCitasLayout.setVerticalGroup(
            pnlCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAfiliacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(pnlAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(pnlCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 51, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Formulario Hospital");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnl_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
       OcultarPanel();
       pnlPaciente.setVisible(true);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfiliacionActionPerformed
       OcultarPanel();
       pnlAfiliacion.setVisible(true);
    }//GEN-LAST:event_btnAfiliacionActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        OcultarPanel();
       pnlCitas.setVisible(true);
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        GuardarRegistroPaciente();
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void txt_IdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdentificacionActionPerformed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        BuscarRegistroPaciente();
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void txt_NombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombActionPerformed

    private void txt_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaActionPerformed

    private void txt_ApellidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidActionPerformed

    private void btn_GuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardActionPerformed
        GuardarRegistroAfiliacion();
    }//GEN-LAST:event_btn_GuardActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        ActualizarAfiliacion();
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_BuscarAfiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarAfiliActionPerformed
        BuscarRegistroAfiliacion();
    }//GEN-LAST:event_btn_BuscarAfiliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfiliacion;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_BuscarAfili;
    private javax.swing.JButton btn_Guard;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JComboBox<String> cbx_EPS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbIdentificacionl;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lbl_Afiliacion;
    private javax.swing.JLabel lbl_Apell;
    private javax.swing.JLabel lbl_EPS;
    private javax.swing.JLabel lbl_Fecha;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_Nomb;
    private javax.swing.JPanel pnlAfiliacion;
    private javax.swing.JPanel pnlCitas;
    private javax.swing.JPanel pnlPaciente;
    private javax.swing.JPanel pnl_Menu;
    private javax.swing.JTextField txt_Apellid;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Fecha;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Identificacion;
    private javax.swing.JTextField txt_Nomb;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
